export const hopUrl = 'https://kovan.hop.exchange/'
export const discordUrl = 'https://discord.gg/2BxafMKP'
export const docsUrl = 'https://docs.hop.exchange/'
export const githubUrl = 'https://github.com/hop-protocol'
export const twitterUrl = 'https://twitter.com/HopProtocol'
