export const hopUrl = 'https://app.hop.exchange/'
export const discordUrl = 'https://discord.gg/PwCF88emV4'
export const docsUrl = 'https://docs.hop.exchange/'
export const faqUrl = 'https://help.hop.exchange/hc/en-us'
export const githubUrl = 'https://github.com/hop-protocol'
export const mediumUrl = 'https://medium.com/hop-protocol'
export const twitterUrl = 'https://twitter.com/HopProtocol'
